baseURL: "https://blog.kongjun-net.xyz" # FIXME: 使用正确网址
defaultContentLanguage: "zh-cn" # 默认语言为中文
languageCode: "zh-CN" #　使用中文
hasCJKLanguage: true # 启用对东亚文字的支持
title: "孔俊的知识库" # 浏览器标签名
theme: "FixIt" # 主题
summaryLength: 180
params: # 覆盖默认选项
  version: "0.2.x" # FixIt v0.2.x 版本
  defaultTheme: "auto" # FixIt 默认样式为 auto
  gitRepo: "https://github.com/kongjun18/blog" # 源代码 Github 网址
  externalIcon: true # 启用外链
  autoBookmark: true # 关闭页面时保存阅读进度
  header:
    title:
      name: "孔俊的知识库" # 网址 header 标题
  footer:
    license: "All rights reserved" # copyright
    since: 2022 # 网站创建时间
  author: # 作者信息，用于 archetypes 模版
    name: "Kong Jun"
    email: "kongjun18@outlook.com"
    link: "https://github.com/kongjun18"
  home:
    profile:
      gravatarEmail: "kongjun18@outlook.com" # gravatar 邮箱
      avatarURL: "/site/avatar.png" # 头像图片
      subtitle: "记录探索的过程" # 头像下的文字
  social:
    Github: "kongjun18"
    Email: "kongjun18@outlook.com"
  pangu:
    enable: true # 自动开启盘古插件
  githubCorner: # 在右上角显示博客 Github 链接
    enable: true
    permalink: "https://github.com/kongjun18/blog"
    title: "查看博客源代码"
    position: "left"
menu:
  main:
    - identifier: "posts"
      pre: ""
      post: ""
      name: "文章"
      url: "/posts/"
      title: ""
      weight: 1
    - identifier: "categories"
      pre: ""
      post: ""
      name: "分类"
      url: "/categories/"
      title: ""
      weight: 2
    - identifier: "tags"
      pre: ""
      post: ""
      name: "标签"
      url: "/tags/"
      title: ""
      weight: 3
markup:
  highlight:
    noClasses: false
